services:

  postgres:
    container_name: postgres
    image: postgres:latest
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql